import pygame

pygame.mixer.init()
collect_coin_sound = pygame.mixer.Sound('collect_sound.wav')
collect_coin_sound.set_volume(0.1)
collect_fruit_sound = pygame.mixer.Sound('collect_2_sound.wav')
collect_fruit_sound.set_volume(0.1)
background_music = pygame.mixer.Sound('game_music.mp3')
background_music.set_volume(0.4)
jump_sound = pygame.mixer.Sound('jump2_sound.wav')
jump_sound.set_volume(0.2)
bounce_sound = pygame.mixer.Sound('bounce_sound.wav')
bounce_sound.set_volume(0.2)
tap_sound = pygame.mixer.Sound('tap_sound.wav')
tap_sound.set_volume(0.2)
death_sound = pygame.mixer.Sound('die_sound.mp3')
death_sound.set_volume(0.2)
run_sound = pygame.mixer.Sound('run_sound.mp3')
run_sound.set_volume(0.3)
run_sound_play = 1
buy_sound = pygame.mixer.Sound('buy_sound.mp3')
buy_sound.set_volume(0.3)
declined_sound = pygame.mixer.Sound('declined_sound.mp3')
declined_sound.set_volume(0.3)